apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app_1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Titrox/argo-examples
    targetRevision: HEAD
    path: app-of-apps/apps/app_1
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
