apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:

        - list:
            elements:
              - env: dev
                namespace: dev
              - env: nonprod
                namespace: nonprod
              - env: prod
                namespace: prod

        - git:
            repoURL: https://github.com/Titrox/argo-examples
            revision: HEAD
            directories:
              - path: 'ApplicationSet/apps/*'

  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      source:
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - values-{{env}}.yaml 

      destination:
        namespace: '{{namespace}}'
      
      syncPolicy:
        automated:
          prune: true
        syncOptions:
            - CreateNamespace=true