apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
spec:
  generators:

        - git:
            repoURL: https://github.com/Titrox/argo-examples
            revision: HEAD
            directories:
            - path: 'ApplicationSet/apps/*/values-dev.yaml' # this will match all directories under apps that contain a values-dev.yaml file, applicationSet will ONLY manage dev environment

  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      source:
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
            - values-dev.yaml
        
        repoURL: https://github.com/Titrox/argo-examples
      
      project: default

      destination:
        namespace: '{{namespace}}'
        server: https://kubernetes.default.svc
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true