app:
  name: app1
  namespace: argocd

source:
  repoURL: https://github.com/Titrox/argo-examples
  targetRevision: HEAD
  path: ApplicationSet/apps/app1

destination:
  server: https://kubernetes.default.svc
  namespace: app1

project: default

syncPolicy:
  automated:
    prune: true
    selfHeal: true
